# Generated by Django 3.2.6 on 2021-08-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='datails',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
