# Generated by Django 3.2.6 on 2021-08-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210825_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='datails',
            new_name='details',
        ),
    ]
